# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0296391b1f4c6c1d3cfcab1506aff81183e513831f78af55a6c389911fd2785898c9e5be47efcc5f95fc36deb67467ee05d4f3211793257bcf69e1adf8e3ef28

test:
  secret_key_base: 211baf644b3add5b68178db2c6d0c515ad6020ed6d3262bcb4ce4ffd98c7b6a4ff62f428c415056f4d28216c2ca12edadc9814e37ceb20018906932f4bbbc771

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
